spring:
    datasource:
        url: jdbc:h2:file:~/mapping_jpa_db
        username: sa
        password: 
    jpa:
        hibernate:
            ddl-auto: create
    h2:
        console:
            enabled: true